import Background from "@/components/Background";
import Footer from "@/components/Footer";
import Info from "@/components/Info";
import MaxWrapper from "@/components/MaxWrapper";
import SecondaryWrapper from "@/components/SecondaryWrapper";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <MaxWrapper>
            <SecondaryWrapper>
              <Background />
              <Info />
            </SecondaryWrapper>
          </MaxWrapper>
        </div>
      </main>
    </>
  );
}
